class InterestBearingItem: ...
class Asset: ...
class Insurabletem: ...
class RealEstate(Insurabletem, Asset): ...
class BankAccount(InterestBearingItem, Insurabletem, Asset): ...
class Security(Asset, InterestBearingItem): ...
class Bond(Security): ...
class Stock(Security): ...
class SavingAccount(BankAccount): ...
class CheckingAccount(BankAccount): ...